name: Build K2P-5.0 512M Ultimate

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
        sudo apt-get -y install python3-docutils lib32z1

    - name: Clone source code
      run: |
        cd toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/

    - name: Build Firmware
      run: |
        cwd=`pwd`
        CONFIG_TOOLCHAIN_DIR=${cwd//\//\\\/}\\/toolchain-mipsel
        
        # 1. 修复 Go 环境
        mkdir -p trunk/tools/go
        curl -L https://golang.org/dl/go1.15.2.linux-amd64.tar.gz -o trunk/tools/go/go1.15.2.linux-amd64.tar.gz
        cd trunk/tools/go
        tar -C . -xzf go1.15.2.linux-amd64.tar.gz
        mkdir -p bin
        ln -sf ../go/bin/go bin/go 
        cd ../../../
        
        # 2. 配置机型
        cd trunk
        m="K2P-5.0" 
        cp -f configs/templates/$m.config .config
        
        # 3. 救命补丁：禁用失效的 htop 插件，防止编译中断
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_HTOP=y/CONFIG_FIRMWARE_INCLUDE_HTOP=n/' .config
        echo "CONFIG_FIRMWARE_INCLUDE_HTOP=n" >> .config
        
        # 4. 强制注入 512M 及功能参数
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_512MB_RAM=n/CONFIG_FIRMWARE_INCLUDE_512MB_RAM=y/' .config
        echo "CONFIG_FIRMWARE_INCLUDE_512MB_RAM=y" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_CLASH=y" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y" >> .config
        echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=y" >> .config
        echo "CONFIG_FIRMWARE_ENABLE_USB=n" >> .config
        
        # 5. 执行编译
        sed -i "s/^CONFIG_TOOLCHAIN_DIR=.*$/CONFIG_TOOLCHAIN_DIR=${CONFIG_TOOLCHAIN_DIR}/g" .config
        sudo ./clear_tree_simple
        sudo ./build_firmware_modify $m 0
        sudo mv -f images/*.trx /opt/images/

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: K2P_512M_Custom_Firmware
        path: /opt/images/*.trx
